#!/bin/sh

# cleanup script borrowed and adapted from the RcppGSL package 

rm -f  config.log config.status confdefs.h \
       src/*.o src/*.so src/Makevars \
       src/modules/*.o src/modules/*.oct\
       inst/doc/*.blg inst/doc/*.bbl \
       */*~ *~ 
rm -rf autom4te.cache inst/doc/*/auto

#(cd inst/examples/RcppGSLExample;  \
#    rm -f  config.log config.status  \
#           src/*.o src/*.so src/Makevars \
#           */*~ *~ ; \
#    rm -rf autom4te.cache)